model_list:
  - model_name: "llama3.2"
    litellm_params:
      model: "ollama_chat/llama3.2"
      api_base: "http://ollama:11434"

general_settings:
  master_key: sk-1234
  database_url: postgres://litellm:secret@db:5432/litellm
